suppression_policies:
  - message_name: welcome
    max_sends: 1
    period: lifetime

  - message_name: insufficient_funds
    max_sends: 1
    period: calendar_day

  - message_name: bank_account_ready
    max_sends: 1
    period: lifetime