message_suppression_policies:
  - message: welcome
    max_sends: 1
    period: lifetime

  - message: insufficient_funds
    max_sends: 1
    period: calendar_day

  - message: bank_account_ready
    max_sends: 1
    period: lifetime